#!/bin/bash
set -e pipefail

echo "This file should be imported into your current shell via 'source ./0_prereqs'"

export RANDOM_ID="$(openssl rand -hex 3)"
export MY_RESOURCE_GROUP_NAME="myAKSResourceGroup$RANDOM_ID"
export REGION="westeurope"
export MY_AKS_CLUSTER_NAME="myAKSCluster$RANDOM_ID"
export MY_DNS_LABEL="mydnslabel$RANDOM_ID"

echo
echo "RANDOM_ID=$RANDOM_ID | MY_RESOURCE_GROUP_NAME=$MY_RESOURCE_GROUP_NAME"
echo "REGION=$REGION | MY_AKS_CLUSTER_NAME=$MY_AKS_CLUSTER_NAME"
echo "MY_DNS_LABEL=$MY_DNS_LABEL"
